

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 1000000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    # url: jdbc:postgresql://localhost:5432/hr_work
    url: jdbc:postgresql://localhost:5432/hr_work?rewriteBatchedStatements=true
    username:
    password:
    driver-class-name: org.postgresql.Driver
logging:
  level:
    root: info
    sql: off
    org:
      hibernate: OFF
    com:
      zaxxer:
        hikari: OFF
      mysql: OFF
    MySQL: OFF
server:
  port: 9232
